### ISSUE TITLE
Differential Rigid body papers

### ISSUE THREAD

**Issue by DuaneNielsen** [thunil/Physics-Based-Deep-Learning#2]
**End-to-End Differentiable Physics for Learning and Control** [paper](http://papers.nips.cc/paper/7948-end-to-end-differentiable-physics-for-learning-and-control) [code](https://github.com/locuslab/lcp-physics)

**Interactive Differentiable Simulation** [paper](https://arxiv.org/abs/1905.10706) [code](https://github.com/google-research/tiny-differentiable-simulator)

**Comment by thunil** [comment]
Thanks for the links!
