### ISSUE TITLE
Additional links

### ISSUE THREAD

**Issue by akasharidas** [thunil/Physics-Based-Deep-Learning#5]
Paper:
1. Deep neural networks to correct sub-precision errors in CFD (https://www.sciencedirect.com/science/article/pii/S2666352X22000243 / https://arxiv.org/abs/2202.04233)

Frameworks:
1. JAX-CFD (https://github.com/google/jax-cfd)
2. JAXFLUIDS (https://github.com/tumaer/JAXFLUIDS)

**Comment by thunil** [comment]
Thanks, added!
